basePath: /api/v1
definitions:
  models.Response:
    properties:
      data: {}
      error: {}
      message:
        type: string
      status:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: WELCOME TO ECHO-HUB
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: ECHO-HUB-SOCIAL-MEADIA
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - multipart/form-data
      description: Register a new user with the provided information
      parameters:
      - description: User's email address
        in: formData
        name: email
        required: true
        type: string
      - description: User's password
        in: formData
        name: password
        required: true
        type: string
      - description: User's phone number
        in: formData
        name: phonenum
        required: true
        type: string
      - description: User's username
        in: formData
        name: username
        required: true
        type: string
      - description: User's bio
        in: formData
        name: bio
        type: string
      - description: User's gender
        in: formData
        name: gender
        type: string
      - description: User's profile picture
        in: formData
        name: profile_picture
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Response'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/models.Response'
      summary: Register a new user
      tags:
      - Authentication
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
